# -*- coding: utf-8 -*-
"""Copy of clustering+MMR 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tvy8VJvgG4SYMWpCEFGmmnYj1AMvSUEo
"""

!pip install transformers torch scikit-learn networkx nltk

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import torch
import re
import networkx as nx
import nltk

from nltk.tokenize import sent_tokenize
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans

nltk.download('punkt')
nltk.download('punkt_tab')

file_path = "/content/drive/MyDrive/preprocessed_train.csv"
df = pd.read_csv(file_path)

model_name = "nlpaueb/legal-bert-base-uncased"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)
model.eval()

def get_sentence_embedding(sentence):
    inputs = tokenizer(sentence,
                       return_tensors="pt",
                       truncation=True,
                       padding=True,
                       max_length=512)
    with torch.no_grad():
        outputs = model(**inputs)
    return outputs.last_hidden_state[:, 0, :].squeeze().numpy()

def summarize_document(original_doc, ratio=0.40, lambda_param=0.7):

    # Sentence Splitting
    sentences_original = sent_tokenize(original_doc)
    sentences_original = [s.strip() for s in sentences_original if len(s.strip()) > 20]

    if len(sentences_original) < 2:
        return original_doc

    # Clean for embeddings
    def clean_sentence(text):
        text = text.lower()
        text = re.sub(r'[^a-z0-9 ]', '', text)
        text = re.sub(r'\s+', ' ', text)
        return text.strip()

    sentences_clean = [clean_sentence(s) for s in sentences_original]

    # Generate embeddings
    sentence_embeddings = np.array(
        [get_sentence_embedding(s) for s in sentences_clean]
    )

    # ---------------------------
    # TextRank Importance (FIXED)
    # ---------------------------
    similarity_matrix = cosine_similarity(sentence_embeddings)

    # Remove self-similarity dominance
    np.fill_diagonal(similarity_matrix, 0)

    nx_graph = nx.from_numpy_array(similarity_matrix)

    try:
        scores = nx.pagerank(nx_graph, max_iter=500, tol=1e-06)
    except:
        print("PageRank failed, using fallback uniform scores.")
        scores = {i: 1.0 for i in range(len(sentences_original))}

    # ---------------------------
    # Clustering (Structure)
    # ---------------------------
    num_sentences = len(sentences_original)
    k = min(4, num_sentences)

    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(sentence_embeddings)

    selected = []

    # Select one representative per cluster
    for cluster_id in range(k):
        cluster_indices = [i for i in range(num_sentences)
                           if cluster_labels[i] == cluster_id]
        if cluster_indices:
            best_idx = max(cluster_indices, key=lambda i: scores[i])
            selected.append(best_idx)

    # ---------------------------
    # Word limit (40%)
    # ---------------------------
    original_word_count = len(original_doc.split())
    word_limit = int(original_word_count * ratio)

    current_word_count = sum(len(sentences_original[i].split()) for i in selected)

    # ---------------------------
    # MMR Refinement
    # ---------------------------
    remaining = [i for i in range(num_sentences) if i not in selected]

    while remaining and current_word_count < word_limit:

        mmr_scores = []

        for i in remaining:
            importance = scores[i]

            similarity_to_selected = max(
                cosine_similarity(
                    [sentence_embeddings[i]],
                    [sentence_embeddings[j]]
                )[0][0]
                for j in selected
            )

            mmr_score = lambda_param * importance - (1 - lambda_param) * similarity_to_selected

            mmr_scores.append((mmr_score, i))

        mmr_scores.sort(reverse=True)
        best_score, best_idx = mmr_scores[0]

        sentence_length = len(sentences_original[best_idx].split())

        if current_word_count + sentence_length <= word_limit:
            selected.append(best_idx)
            current_word_count += sentence_length

        remaining.remove(best_idx)

    selected = sorted(selected)

    summary = " ".join([sentences_original[i] for i in selected])

    return summary

for i in range(5):

    original_doc = df['original_text'].iloc[i]
    summary = summarize_document(original_doc)

    original_word_count = len(original_doc.split())
    summary_word_count = len(summary.split())
    compression_ratio = round((summary_word_count / original_word_count) * 100, 2)

    print("\n" + "="*80)
    print(f"DOCUMENT {i+1}")
    print("="*80)

    print("\nORIGINAL WORD COUNT:", original_word_count)
    print("SUMMARY WORD COUNT:", summary_word_count)
    print("COMPRESSION %:", compression_ratio, "%")

    print("\nSUMMARY:\n")
    print(summary)

!pip install transformers torch scikit-learn nltk

import torch
import numpy as np
import pandas as pd
import re
import nltk

from nltk.tokenize import sent_tokenize
from transformers import AutoTokenizer, AutoModel
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.cluster import KMeans

nltk.download("punkt")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name = "nlpaueb/legal-bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name).to(device)
model.eval()

file_path = "/content/drive/MyDrive/preprocessed_100_docs.csv"
df = pd.read_csv(file_path)

def get_sentence_embeddings_batch(sentences, batch_size=16):
    all_embeddings = []

    for i in range(0, len(sentences), batch_size):
        batch = sentences[i:i+batch_size]

        inputs = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=128,
            return_tensors="pt"
        ).to(device)

        with torch.no_grad():
            outputs = model(**inputs)

        emb = outputs.last_hidden_state[:, 0, :]
        all_embeddings.append(emb.cpu())

    return torch.cat(all_embeddings).numpy()

def textrank_scores(sim, iters=20, d=0.85):
    n = sim.shape[0]
    scores = np.ones(n) / n
    sim = sim / (sim.sum(axis=1, keepdims=True) + 1e-9)

    for _ in range(iters):
        scores = (1 - d) + d * sim.T @ scores

    return scores

def is_boilerplate(sentence):
    patterns = [
        r'case\s+\d',
        r'document\s+\d',
        r'filed\s+\d',
        r'entered:',
        r'pacer',
        r'docket',
        r'civil cover sheet',
        r'summons',
        r'attachment',
        r'u\.s\. district court',
        r'clerk of court',
        r'notice of electronic filing'
    ]
    sentence = sentence.lower()
    return any(re.search(p, sentence) for p in patterns)

def is_legal_noise(sentence):
    s = sentence.lower()

    # address blocks
    if re.search(r'\b(po box|box \d+|street|avenue|road|suite|ca \d{5}|dc \d{5})\b', s):
        return True

    # phone numbers
    if re.search(r'\(\d{3}\)\s*\d{3}[-–]\d{4}', s):
        return True

    # party captions (short lines with roles)
    if re.search(r'plaintiff|defendant|petitioner|respondent', s) and len(s.split()) < 15:
        return True

    # ALL CAPS headings
    if sentence.isupper() and len(sentence.split()) < 20:
        return True

    return False

def summarize_document_fast(doc, ratio=0.4, lambda_param=0.7):

    sentences = [
    s.strip()
    for s in sent_tokenize(doc)
    if 10 <= len(s.split()) <= 40
    and not is_boilerplate(s)
    and not is_legal_noise(s)
]
    if len(sentences) < 2:
        return doc

    def clean(s):
        s = s.lower()
        s = re.sub(r'[^a-z0-9 ]', '', s)
        return s

    clean_sentences = [clean(s) for s in sentences]

    # ---- Batch embeddings ----
    embeddings = get_sentence_embeddings_batch(clean_sentences)

    # ---- Similarity ----
    sim_matrix = cosine_similarity(embeddings)
    np.fill_diagonal(sim_matrix, 0)

    # ---- Importance ----
    scores = textrank_scores(sim_matrix)

    # ---- Clustering ----
    k = min(4, len(sentences))
    labels = KMeans(n_clusters=k, random_state=42, n_init=5)\
                .fit_predict(embeddings)

    selected = []
    for c in range(k):
        idx = np.where(labels == c)[0]
        best = idx[np.argmax(scores[idx])]
        selected.append(best)

    # ---- Word limit ----
    word_limit = int(len(doc.split()) * ratio)
    current_words = sum(len(sentences[i].split()) for i in selected)

    remaining = list(set(range(len(sentences))) - set(selected))

    # ---- FAST MMR (precomputed similarity) ----
    while remaining and current_words < word_limit:
        mmr_vals = []

        for i in remaining:
            sim_to_sel = max(sim_matrix[i][j] for j in selected)
            mmr = lambda_param * scores[i] - (1 - lambda_param) * sim_to_sel
            mmr_vals.append((mmr, i))

        _, best = max(mmr_vals)

        sent_len = len(sentences[best].split())
        if current_words + sent_len <= word_limit:
            selected.append(best)
            current_words += sent_len

        remaining.remove(best)

    selected.sort()
    return " ".join(sentences[i] for i in selected)

doc = df['original_text'].iloc[0]

summary = summarize_document_fast(doc, ratio=0.08)

print("Original words:", len(doc.split()))
print("Summary words:", len(summary.split()))
print("\nSUMMARY:\n")
print(summary)

import time

start = time.time()
summary = summarize_document_fast(doc)
print("Time taken:", round(time.time() - start, 2), "seconds")

for i in range(5):
    doc = df['original_text'].iloc[i]
    summary = summarize_document_fast(doc, ratio=0.08)

    print("\n" + "="*80)
    print(f"DOCUMENT {i+1}")
    print("Original:", len(doc.split()),
          "Summary:", len(summary.split()))

import time

doc = df['original_text'].iloc[0]

start = time.time()
_ = summarize_document_fast(doc, ratio=0.08)
print("Time for ONE document:", round(time.time() - start, 2), "sec")

print("Expected time for 5 docs:",
      round(5 * (time.time() - start) / 60, 2), "minutes")

summaries = []

for i in range(5):
    print(f"Processing document {i+1}/5")
    start = time.time()

    doc = df['original_text'].iloc[i]
    summary = summarize_document_fast(doc, ratio=0.08)
    summaries.append(summary)

    print("Time:", round(time.time() - start, 2), "sec")

df.loc[:4, 'summary'] = summaries

for i in range(5):
    doc = df['original_text'].iloc[i]
    sentences = [s for s in sent_tokenize(doc) if len(s.split()) > 5]
    print(f"Doc {i+1} sentence count:", len(sentences))

df.to_csv("/content/drive/MyDrive/summarized_docs.csv", index=False)